artifact_root: data

data_ingestion:
  root_dir : data/raw
  Train_data_path: data/raw/train.csv
  test_data :  data/raw/test.csv
  data_source: 'https://raw.githubusercontent.com/AyushAI14/Test-dataset/refs/heads/main/IMDB.csv'

data_transformation:
  root_dir : data/interim
  Train_data_path: data/raw/train.csv
  test_data :  data/raw/test.csv
  clean_Train_data_path: data/interim/train.csv
  clean_test_data :  data/interim/test.csv

feature_Engineering:
  root_dir : data/processed
  process_Train_data_path: data/processed/train.csv
  process_test_data :  data/processed/test.csv
  clean_Train_data_path: data/interim/train.csv
  clean_test_data :  data/interim/test.csv

model_building:
  process_Train_data_path: data/processed/train.csv
  process_test_data :  data/processed/test.csv

model_evalution:
  process_test_data: data/processed/test.csv
  model_path: models/clfLR.pkl

model_registry:
  json_file: reports/experiment_info.json